//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public int MainCategoryId { get; set; }
        public int SizeId { get; set; }
        public int BrandId { get; set; }
        public int DestinationId { get; set; }
        public int ColourId { get; set; }
        public string Code { get; set; }
		public string Name { get; set; }
        public double Price { get; set; }
        public DateTime? FabricationDate { get; set; }
        public DateTime? ExpireDate { get; set; }
		public virtual ICollection<ProductSubCategories> ProductSubCategories { get; set; }
    }
}
