//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clothing_Stock
    {
        public int Id { get; set; }
        public string Size { get; set; }
        public int ClothingId { get; set; }
        public int Stock { get; set; }
    
        public virtual Clothing Clothing { get; set; }
    }
}
