//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clothing
    {
        public Clothing()
        {
            this.Clothing_Stock = new HashSet<Clothing_Stock>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int BrandId { get; set; }
        public int GenderId { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Clothing_Brand Clothing_Brand { get; set; }
        public virtual Clothing_Category Clothing_Category { get; set; }
        public virtual Clothing_Gender Clothing_Gender { get; set; }
        public virtual ICollection<Clothing_Stock> Clothing_Stock { get; set; }
    }
}
